name: 'Dummy workflow'

on:
  repository_dispatch:
    types: [ok-to-test-command]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy
        run: echo "DUMMY!!!!!"

      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Code Lint
        run: make tools && make lint
      - name: Website
        run: make tools && make website-lint
      - name: Test
        run: make test
